language: go

go: 
 - 1.13
 
env: GO111MODULE=on

script: GOARCH=amd64 go build -o webp-server-linux-amd64 webp-server.go

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file:
      - webp-server
  on:
      repo: webp-sh/webp_server_go
      tags: true
      branch: add-travis-ci