language: go

go: 
 - 1.13

jobs:
  include:
    - stage: test-build
      script: go build -o webp-server-linux-amd64 webp-server.go
      script: ls

    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file:
            - webp-server
        on:
            repo: webp-sh/webp_server_go
            tags: false
            branch: add-travis-ci